### ISSUE TITLE
Unable to set Gradient prop on IOS, is this expected behavior for LFHeatMap?

### ISSUE THREAD

**Issue by jacksonjw12** [cawfree/react-native-heat-map#5]
Hello, I recently implemented your heatmap library into my project(was very impressive!), but I was unable to alter the default gradient properties. I looked through some of the calls this library makes to LFHeatMap, but I didn't locate where the gradient object was being passed to the native component.  If you could either confirm that on IOS gradients should not be working, or maybe point out if I am passing the gradient prop wrong, it would be greatly appreciated.
Thanks!
# Info: 
## My projects dependencies, and versions
"dependencies": {
    "@cawfree/react-native-heat-map": "0.0.2",
    "@react-native-community/async-storage": "^1.11.0",
    "react": "16.13.1",
    "react-native": "0.63.2",
    "react-native-elements": "^2.2.1",
    "react-native-maps": "^0.27.1",
    "react-native-vector-icons": "^7.0.0",
    "react-native-webview": "^10.4.1",
    "react-redux": "^7.2.1"
  },

### react-native-maps MapView Component

     render() {
         const {viewStyle, reports} = this.state;
         return (
            <View style={styles.container}>
                <MapView
                    style={styles.map}
                    provider={this.provider}
                    region={this.state.region}
                    onRegionChange={this.onRegionChange}
                    onRegionChangeComplete={this.onRegionComplete}
                >
                    

                    { (viewStyle == "points")
                    ? this.renderPointMarkers(reports.reportsObj)
                    : this.renderHeatMap(reports.reportsArray)
                    }

                </MapView>
                
                
            </View>
        );
    }

### HeatMap

```
    renderHeatMap(reportsArray){
        const {regionCopy, region} = this.state;
        return (
        <Marker
            ref="heatMapCenter"
            coordinate={region}
        >
            <View style={styles.container}>
                <View style={styles.heatMapContainer} pointerEvents="none">
                    <HeatMap
                        ref="heatMap"
                        // pointerEvents="none"
                        style={{flex: 1,width:Dimensions.get('window').width * 0.8,height:Dimensions.get('window').width * 0.8}}
    
                        // opacity={0.7}
                        gradient={{
                            0.0: 'blue',
                            0.2: 'cyan',
                            0.4: 'green',
                            0.6: 'yellow',
                            0.8: 'green',
                          }}
                        alpha={0.8}
                        max={5.0}
                        radius={60}
                        minOpacity= {0.05}
                        data={reportsArray}
                        region={region}
                    />
                </View>
            </View>
        </Marker>
           
     )}
```

# Thanks for taking a look at this issue!
Let me know if you need any more information from me
Also, if you happen to have a link to an example implementation of this repo working alongside react-native-maps, that would be very helpful. (I've already gone through the example directories for this library, and the simpleheat react-native library you also authored)

# Screenshot
### Here is the results I am getting currently when running on an iPhone (would have expected to see colors relating to the gradient object that I passed in)

![image](https://user-images.githubusercontent.com/5806985/90299618-9744bf80-de4b-11ea-9add-76533d1bb5e1.png)

**Comment by cawfree** [comment]
Hey @jacksonjw12👋 

It’s really cool to see your work!  Thank you so much for the detailed documentation!

Unfortunately at this time, iOS uses a separate heat map implementation than Android. My Objective C skills just weren’t there to translating SimpleHeat back when I wrote this.

More than happy to help with a PR if you feel like taking this on? ✊🚀

**Comment by jacksonjw12** [comment]
Thanks for a response! Im looking at a few different solutions, but if I end up trying to modify your library I will definitely submit a pull request.
